In [ ]:
# Importation des librairies
import numpy as np  # Utilisé pour les opérations numériques
import matplotlib.pyplot as plt # Utilisé pour le tracé de graphiques
import pandas as pd # Utilisé pour la manipulation de données
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix # Utilisé pour l'évaluation du modèle
from sklearn.model_selection import cross_val_score # Utilisé pour la validation croisée



In [ ]:
# Importation du jeu de données
dataset = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')  # Importation du jeu de données en utilisant pandas
dataset # Affichage du jeu de données

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
dataset['Geography']= dataset['Geography'].replace({'France':0, 'Spain':1, 'Germany':2}) # Remplacement des valeurs catégorielles par des valeurs numériques pour la colonne Geography
dataset['Geography']= dataset['Geography'].astype('category') # Conversion de la colonne Geography en type catégoriel
dataset['Geography'] = dataset['Geography'].cat.codes # Encodage des valeurs catégorielles
dataset['Gender']= dataset['Gender'].replace({'Male':0, 'Female':1}) # Remplacement des valeurs catégorielles par des valeurs numériques pour la colonne Gender
dataset['Gender']= dataset['Gender'].astype('category') # Conversion de la colonne Gender en type catégoriel
dataset['Gender'] = dataset['Gender'].cat.codes # Encodage des valeurs catégorielles


In [ ]:
dataset # Affichage du jeu de données

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602   Hargrave          619          0       1   42   
1             2    15647311       Hill          608          1       1   41   
2             3    15619304       Onio          502          0       1   42   
3             4    15701354       Boni          699          0       1   39   
4             5    15737888   Mitchell          850          1       1   43   
...         ...         ...        ...          ...        ...     ...  ...   
9995       9996    15606229   Obijiaku          771          0       0   39   
9996       9997    15569892  Johnstone          516          0       0   35   
9997       9998    15584532        Liu          709          0       1   36   
9998       9999    15682355  Sabbatini          772          2       0   42   
9999      10000    15628319     Walker          792          0       1   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
new_dataset= dataset[['CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Exited']] # Sélection de colonnes spécifiques pour le nouveau jeu de données
new_dataset # Affichage du nouveau jeu de données

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       1   42       2       0.00              1   
1             608          1       1   41       1   83807.86              1   
2             502          0       1   42       8  159660.80              3   
3             699          0       1   39       1       0.00              2   
4             850          1       1   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       0   39       5       0.00              2   
9996          516          0       0   35      10   57369.61              1   
9997          709          0       1   36       7       0.00              1   
9998          772          2       0   42       3   75075.31              2   
9999          792          0       1   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [ ]:
X= new_dataset.drop(columns=['Exited']) # Séparation des caractéristiques (X) de la variable cible
y= dataset['Exited'] # Assignation de la variable cible à y

In [ ]:
X = (X - X.mean()) / X.std() # Standardisation des caractéristiques

In [ ]:
X

CreditScore  Geography    Gender       Age    Tenure   Balance  \
0       -0.326205  -0.902541  1.095933  0.293503 -1.041708 -1.225786   
1       -0.440014   0.301650  1.095933  0.198154 -1.387468  0.117344   
2       -1.536717  -0.902541  1.095933  0.293503  1.032856  1.332987   
3        0.501496  -0.902541  1.095933  0.007456 -1.387468 -1.225786   
4        2.063781   0.301650  1.095933  0.388852 -1.041708  0.785689   
...           ...        ...       ...       ...       ...       ...   
9995     1.246426  -0.902541 -0.912374  0.007456 -0.004426 -1.225786   
9996    -1.391870  -0.902541 -0.912374 -0.373939  1.724377 -0.306363   
9997     0.604958  -0.902541  1.095933 -0.278590  0.687096 -1.225786   
9998     1.256772   1.505841 -0.912374  0.293503 -0.695947 -0.022606   
9999     1.463698  -0.902541  1.095933 -1.041381 -0.350186  0.859922   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911538   0.646059        0.970194         0.021885  
1         -0.911538  -1.547691        0.970194         0.216523  
2          2.526930   0.646059       -1.030619         0.240675  
3          0.807696  -1.547691       -1.030619        -0.108912  
4         -0.911538   0.646059        0.970194        -0.365258  
...             ...        ...             ...              ...  
9995       0.807696   0.646059       -1.030619        -0.066416  
9996      -0.911538   0.646059        0.970194         0.027987  
9997      -0.911538  -1.547691        0.970194        -1.008593  
9998       0.807696   0.646059       -1.030619        -0.125224  
9999      -0.911538   0.646059       -1.030619        -1.076316  

[10000 rows x 10 columns]

In [ ]:
# Division du jeu de données en ensemble d'entraînement et ensemble de test
from sklearn.model_selection import train_test_split # Importation de train_test_split pour diviser le jeu de données
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # Division du jeu de données en ensembles d'entraînement et de test

# Ajustement de XGBoost à l'ensemble d'entraînement

In [ ]:
from xgboost import XGBClassifier # Importation du classificateur XGBoost
classifier = XGBClassifier() # Création d'une instance du classificateur
classifier.fit(X_train, y_train) # Ajustement du classificateur aux données d'entraînement


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
# Prédiction des résultats de l'ensemble de test
y_pred = classifier.predict(X_test) # Prédiction de la variable cible pour l'ensemble de test


# Création de la matrice de confusion

In [ ]:
from sklearn.metrics import confusion_matrix # Importation de confusion_matrix pour l'évaluation du modèle
cm = confusion_matrix(y_test, y_pred) # Création de la matrice de confusion
cm # Affichage de la matrice de confusion

array([[1491,  104],
       [ 192,  213]])

# Calculer les métriques

In [ ]:
accuracy = accuracy_score(y_test, y_pred) # Calcul de la précision
precision = precision_score(y_test, y_pred) # Calcul de la précision
recall = recall_score(y_test, y_pred) # Calcul du rappel
f1 = f1_score(y_test, y_pred) # Calcul du score F1
confusion_mat = confusion_matrix(y_test, y_pred) # Création de la matrice de confusion


In [ ]:
print("Accuracy:", accuracy) # Affichage de la précision
print("Precision:", precision) # Affichage de la précision
print("Recall:", recall) # Affichage du rappel
print("F1-score:", f1) # Affichage du score F1
print("Confusion matrix:\n", confusion_mat) # Affichage de la matrice de confusion


Accuracy: 0.852
Precision: 0.6719242902208202
Recall: 0.5259259259259259
F1-score: 0.590027700831025
Confusion matrix:
 [[1491  104]
 [ 192  213]]


#Cross-Validation

In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 20)
accuracies.mean()
#accuracies.std()

0.8539999999999999

#Théorie sur l’Équilibrage de Données en Machine Learning : Random Over-Sampling vs SMOTE

*L’équilibrage de données* est une étape clé en Machine Learning, surtout lorsque l’on travaille avec des jeux de données déséquilibrés. Ces déséquilibres se produisent souvent dans des tâches de classification, où certaines classes sont significativement sous-représentées par rapport à d'autres (par exemple, dans la détection de fraudes ou le diagnostic de maladies rares). Pour pallier ce problème, il existe des méthodes telles que le *Random Over-Sampling* et le *SMOTE (Synthetic Minority Over-sampling Technique)*. Ces deux approches visent à rééquilibrer les classes minoritaires, mais elles diffèrent dans leur manière d'y parvenir.

#### 1. *Random Over-Sampling (ROS)* :
Le *Random Over-Sampling* est une méthode simple et intuitive. Elle consiste à dupliquer aléatoirement des exemples de la classe minoritaire afin d'augmenter sa proportion dans le dataset. Cela signifie que certains points de données sont simplement répétés plusieurs fois jusqu'à ce que la classe minoritaire atteigne une fréquence comparable à celle de la classe majoritaire.

- *Avantages* :
  - Facile à implémenter et rapide à exécuter.
  - Aucune nouvelle donnée synthétique n'est générée, ce qui évite le risque de créer des informations incorrectes.

- *Inconvénients* :
  - Augmente la taille du dataset, ce qui peut entraîner un risque de *surapprentissage (overfitting)*, car le modèle pourrait mémoriser des exemples dupliqués au lieu d'apprendre des motifs généralisables.
  - Ne produit aucune nouvelle information, les exemples ajoutés étant des copies exactes des instances existantes.

#### 2. *SMOTE (Synthetic Minority Over-sampling Technique)* :
Le *SMOTE* est une méthode plus sophistiquée qui génère artificiellement de nouveaux exemples pour la classe minoritaire en interpolant entre des exemples réels de cette classe. Pour chaque exemple minoritaire sélectionné, SMOTE crée de nouvelles instances en générant des points de données interpolés qui sont des combinaisons linéaires des voisins proches dans l’espace de caractéristiques.

- *Avantages* :
  - En générant de nouveaux exemples synthétiques, SMOTE réduit le risque de surapprentissage par rapport au Random Over-Sampling, car il introduit de la variabilité dans les données de la classe minoritaire.
  - Les nouveaux points de données synthétiques créent une frontière plus représentative entre les classes, aidant à une meilleure généralisation du modèle.

- *Inconvénients* :
  - Risque de générer des exemples moins fiables ou irréalistes, surtout si les données sont complexes ou bruitées.
  - Peut être plus coûteux en termes de calcul, car il nécessite une étape supplémentaire de génération de données synthétiques.

#### 3. *Comparaison en résumé* :
- *Random Over-Sampling* duplique simplement les exemples existants de la classe minoritaire, ce qui est rapide mais peut causer du surapprentissage.
- *SMOTE* génère de nouvelles instances synthétiques en interpolant entre les exemples minoritaires, ce qui est plus sophistiqué et permet de mieux généraliser, mais cela peut introduire des exemples artificiels qui ne reflètent pas parfaitement la réalité.

#### Conclusion :
Le choix entre Random Over-Sampling et SMOTE dépend du type de données et des exigences du modèle. Si le risque de surapprentissage est élevé et que l’on souhaite une meilleure généralisation, SMOTE est généralement préféré. En revanche, si l'on cherche une solution rapide et simple sans ajout de complexité, le Random Over-Sampling peut suffire.


In [ ]:
new_dataset2= dataset[['CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Exited']]
new_dataset2

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       1   42       2       0.00              1   
1             608          1       1   41       1   83807.86              1   
2             502          0       1   42       8  159660.80              3   
3             699          0       1   39       1       0.00              2   
4             850          1       1   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       0   39       5       0.00              2   
9996          516          0       0   35      10   57369.61              1   
9997          709          0       1   36       7       0.00              1   
9998          772          2       0   42       3   75075.31              2   
9999          792          0       1   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [ ]:
new_dataset2.shape

(10000, 11)

In [ ]:
new_dataset2.Exited.value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
X= new_dataset2.drop(columns=['Exited'])
y= new_dataset2['Exited']

In [ ]:
X = (X - X.mean()) / X.std() # Standardisation des caractéristiques

In [ ]:
X

CreditScore  Geography    Gender       Age    Tenure   Balance  \
0       -0.326205  -0.902541  1.095933  0.293503 -1.041708 -1.225786   
1       -0.440014   0.301650  1.095933  0.198154 -1.387468  0.117344   
2       -1.536717  -0.902541  1.095933  0.293503  1.032856  1.332987   
3        0.501496  -0.902541  1.095933  0.007456 -1.387468 -1.225786   
4        2.063781   0.301650  1.095933  0.388852 -1.041708  0.785689   
...           ...        ...       ...       ...       ...       ...   
9995     1.246426  -0.902541 -0.912374  0.007456 -0.004426 -1.225786   
9996    -1.391870  -0.902541 -0.912374 -0.373939  1.724377 -0.306363   
9997     0.604958  -0.902541  1.095933 -0.278590  0.687096 -1.225786   
9998     1.256772   1.505841 -0.912374  0.293503 -0.695947 -0.022606   
9999     1.463698  -0.902541  1.095933 -1.041381 -0.350186  0.859922   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911538   0.646059        0.970194         0.021885  
1         -0.911538  -1.547691        0.970194         0.216523  
2          2.526930   0.646059       -1.030619         0.240675  
3          0.807696  -1.547691       -1.030619        -0.108912  
4         -0.911538   0.646059        0.970194        -0.365258  
...             ...        ...             ...              ...  
9995       0.807696   0.646059       -1.030619        -0.066416  
9996      -0.911538   0.646059        0.970194         0.027987  
9997      -0.911538  -1.547691        0.970194        -1.008593  
9998       0.807696   0.646059       -1.030619        -0.125224  
9999      -0.911538   0.646059       -1.030619        -1.076316  

[10000 rows x 10 columns]

In [ ]:
!pip install imblearn

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_resample(X, y)
#X_train_smote, y__train_sm = smote.fit_resample(X.astype('float'), y)

In [ ]:
X_train_smote

CreditScore  Geography    Gender       Age    Tenure   Balance  \
0        -0.326205  -0.902541  1.095933  0.293503 -1.041708 -1.225786   
1        -0.440014   0.301650  1.095933  0.198154 -1.387468  0.117344   
2        -1.536717  -0.902541  1.095933  0.293503  1.032856  1.332987   
3         0.501496  -0.902541  1.095933  0.007456 -1.387468 -1.225786   
4         2.063781   0.301650  1.095933  0.388852 -1.041708  0.785689   
...            ...        ...       ...       ...       ...       ...   
15921    -0.289286  -0.902541 -0.912374  0.579720 -0.350186  0.977605   
15922    -1.517627  -0.161917  1.095933  0.469433  1.245512  1.053985   
15923    -0.714015  -0.240916  1.095933  0.259969  1.378617 -1.225786   
15924     0.558748   1.505841 -0.912374  2.507573  0.111048  0.666482   
15925    -0.255890   1.505841  1.095933 -0.288309  0.832935  0.342361   

       NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0          -0.911538   0.646059        0.970194         0.021885  
1          -0.911538  -1.547691        0.970194         0.216523  
2           2.526930   0.646059       -1.030619         0.240675  
3           0.807696  -1.547691       -1.030619        -0.108912  
4          -0.911538   0.646059        0.970194        -0.365258  
...              ...        ...             ...              ...  
15921      -0.911538   0.646059       -1.030619         0.511474  
15922       2.526930   0.646059       -1.030619         1.111879  
15923      -0.911538   0.646059       -1.030619        -0.001488  
15924      -0.911538  -1.547691       -1.030619        -1.530638  
15925      -0.911538   0.646059       -1.030619         0.840333  

[15926 rows x 10 columns]

In [ ]:
from collections import Counter
print("Before SMOTE :",Counter(y))
print("After SMOTE :",Counter(y__train_sm))

Before SMOTE : Counter({0: 7963, 1: 2037})
After SMOTE : Counter({1: 7963, 0: 7963})


In [ ]:
# Division du jeu de données en ensemble d'entraînement et ensemble de test
from sklearn.model_selection import train_test_split # Importation de train_test_split pour diviser le jeu de données
X_train_sm, X_test_sm, y_train_sm, y_test_sm = train_test_split(X_train_smote, y_train_smote, test_size = 0.2, random_state = 0) # Division du jeu de données en ensembles d'entraînement et de test

In [ ]:
from xgboost import XGBClassifier # Importation du classificateur XGBoost
classifier = XGBClassifier() # Création d'une instance du classificateur
classifier.fit(X_train_sm, y_train_sm) # Ajustement du classificateur aux données d'entraînement

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
# Prédiction des résultats de l'ensemble de test
y_pred_sm_Xboost = classifier.predict(X_test_sm) # Prédiction de la variable cible pour l'ensemble de test

In [ ]:
from sklearn.metrics import confusion_matrix # Importation de confusion_matrix pour l'évaluation du modèle
cm = confusion_matrix(y_test_sm, y_pred_sm_Xboost) # Création de la matrice de confusion
cm # Affichage de la matrice de confusion

array([[1456,  134],
       [ 185, 1411]])

In [ ]:
accuracy = accuracy_score(y_test_sm, y_pred_sm_Xboost) # Calcul de la précision
precision = precision_score(y_test_sm, y_pred_sm_Xboost) # Calcul de la précision
recall = recall_score(y_test_sm, y_pred_sm_Xboost) # Calcul du rappel
f1 = f1_score(y_test_sm, y_pred_sm_Xboost) # Calcul du score F1
confusion_mat = confusion_matrix(y_test_sm, y_pred_sm_Xboost) # Création de la matrice de confusion

In [ ]:
print("Accuracy:", accuracy) # Affichage de la précision
print("Precision:", precision) # Affichage de la précision
print("Recall:", recall) # Affichage du rappel
print("F1-score:", f1) # Affichage du score F1
print("Confusion matrix:\n", confusion_mat) # Affichage de la matrice de confusion

Accuracy: 0.8998744507219083
Precision: 0.9132686084142395
Recall: 0.8840852130325815
F1-score: 0.8984399872652021
Confusion matrix:
 [[1456  134]
 [ 185 1411]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=21) #le nombre de K Voisin est égal 3

classifier_knn.fit(X_train_smote, y_train_smote) #Passation de X_train et Y_train dans le modèle

KNeighborsClassifier(n_neighbors=21)

In [ ]:
y_pred_sm_knn = classifier_knn.predict(X_test_sm)

#X_train_sm, X_test_sm, y_train_sm, y_test_sm

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_sm, y_pred_sm_knn)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
# Calculer les métriques
accuracy = accuracy_score(y_test_sm, y_pred_sm_knn)
precision = precision_score(y_test_sm, y_pred_sm_knn, average='weighted')
recall = recall_score(y_test_sm, y_pred_sm_knn, average='weighted')
f1 = f1_score(y_test_sm, y_pred_sm_knn, average='weighted')
confusion_mat = confusion_matrix(y_test_sm, y_pred_sm_knn)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion matrix:\n", confusion_mat)

Accuracy: 0.8283113622096673
Precision: 0.8342469265217879
Recall: 0.8283113622096673
F1-score: 0.8275186225049264
Confusion matrix:
 [[1210  380]
 [ 167 1429]]


SVM: Linear

In [ ]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'linear', random_state = 0)
classifier_svm.fit(X_train_smote, y_train_smote)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred_sm_svm_linear = classifier_svm.predict(X_test_sm)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_sm, y_pred_sm_svm_linear)
cm

array([[1147,  443],
       [ 429, 1167]])

In [ ]:
accuracy = accuracy_score(y_test_sm, y_pred_sm_svm_linear)
precision = precision_score(y_test_sm, y_pred_sm_svm_linear, average='weighted')
recall = recall_score(y_test_sm, y_pred_sm_svm_linear, average='weighted')
f1 = f1_score(y_test_sm, y_pred_sm_svm_linear, average='weighted')
confusion_mat = confusion_matrix(y_test_sm, y_pred_sm_svm_linear)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion matrix:\n", confusion_mat)

Accuracy: 0.7263025737602009
Precision: 0.7263155242333521
Recall: 0.7263025737602009
F1-score: 0.7262950236321691
Confusion matrix:
 [[1147  443]
 [ 429 1167]]


SVM: RBF

In [ ]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel = 'rbf', random_state = 0)
classifier_svm_rbf.fit(X_train_smote, y_train_smote)

SVC(random_state=0)

In [ ]:
y_pred_sm_svm_rbf = classifier_svm_rbf.predict(X_test_sm)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_sm, y_pred_sm_svm_rbf)
cm

array([[1290,  300],
       [ 300, 1296]])

In [ ]:
accuracy = accuracy_score(y_test_sm, y_pred_sm_svm_rbf)
precision = precision_score(y_test_sm, y_pred_sm_svm_rbf, average='weighted')
recall = recall_score(y_test_sm, y_pred_sm_svm_rbf, average='weighted')
f1 = f1_score(y_test_sm, y_pred_sm_svm_rbf, average='weighted')
confusion_mat = confusion_matrix(y_test_sm, y_pred_sm_svm_rbf)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion matrix:\n", confusion_mat)

Accuracy: 0.8116760828625236
Precision: 0.8116760828625236
Recall: 0.8116760828625236
F1-score: 0.8116760828625236
Confusion matrix:
 [[1290  300]
 [ 300 1296]]
